# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-07 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_matchquestion_seek_no_allowed' ),
    ]

    operations = [
        migrations.AlterField(
            model_name='regrecord',
            name='referred_by',
            field=models.CharField(blank=True, max_length=80, verbose_name=b'Referred By'),
        ),
    ]
