# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-24 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_auto_20170807_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchquestion',
            name='absolute_match',
            field=models.BooleanField(default=False),
        ),
    ]
