# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-25 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_matchquestion_absolute_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='regrecord',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regrecord',
            name='volunteers_ok',
            field=models.BooleanField(default=True, verbose_name=b'Dating volunteers and staff is OK (Y/N)'),
        ),
    ]
