# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-01 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_event_free_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchquestion',
            name='seek_no_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
