# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-25 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20180524_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regrecord',
            name='volunteers_ok',
            field=models.BooleanField(default=False, verbose_name=b'Dating volunteers and staff is OK (Y/N)'),
        ),
    ]
