# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-10-05 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20180524_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='text_match_seek',
            field=models.TextField(blank=True, verbose_name=b'Match Criterion for Seek'),
        ),
    ]
