# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-05 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_person_text_match_seek'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='numrounds',
            field=models.IntegerField(default=14, verbose_name=b'Number of dating rounds'),
        ),
    ]
