# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-29 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20190107_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablerecord',
            name='description',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
