# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-02 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_tablerecord_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchquestion',
            name='yes_only',
            field=models.BooleanField(default=False),
        ),
    ]
