# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-05 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20190831_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daterecord',
            name='notes',
        ),
    ]
