# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-10-11 10:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_remove_daterecord_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='curround',
            field=models.IntegerField(default=0, verbose_name=b'Current round (0 means event not started)'),
        ),
        migrations.AddField(
            model_name='event',
            name='curroundend',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 11, 6, 56, 3, 96859)),
            preserve_default=False,
        ),
    ]
